title:            WP-Optimize
description:      Ultimate WordPress Cleanup and Optimization Tool.
logo:             site-logo.png
disqus_shortname: 
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url: http://ruhanirabin.github.io/WP-Optimize

# Owner/author information
owner:
  name:           Ruhani Rabin
  avatar:         bio-photo.jpg
  email:          get@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: ruhanirabin       
  facebook: ruhani.rabin      
  github: ruhanirabin         
  stackexchange:  
  linkedin: ruhanirabin      
  instagram: imthedoctor     
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Translations
    url: /translations/
#  - title: Theme Setup
#    url: /theme-setup/
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kuala_lumpur
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
